### ISSUE TITLE
Automatically relocate package in Kotlin module files when moving packages

### ISSUE THREAD

**Issue by elizarov** [GradleUp/shadow#843]
Kotlin keeps additional package metadata in `.kotlin_module` files; however, these files are not adjusted automatically when `relocate` function of shadow plugin is used. This does not prevent proper usage of the resulting libraries at runtime, but can cause issues if you try to compile Kotlin code against libraries with such relocated packages, as Kotlin compiler uses this metadata to filter out packages. 

There is a [`kotlinx-metadata-jvm`](https://github.com/JetBrains/kotlin/blob/master/libraries/kotlinx-metadata/jvm/ReadMe.md) library that can manipulate (read/write) Kotlin metadata, including `.kotlin_module` files. I can make a PR to support automatic package relocation in Kotlin metadata when `relocate` is used. Will you accept this sort of contribution?

**Comment by Goooler** [comment]
Good to see!

**Comment by johnrengelman** [comment]
@elizarov I'd be happy to take a look at a PR.
My gut is telling me that based on how complex that support is, that I might want to take this time to see if there is a way to have Shadow be extending in a way that makes adding this type of language specific support be added externally instead of in the main library. Would you be willing to work through that process? (My time is pretty small to work on this, so it could drag on, but if you're willing, we can try).

**Comment by DreierF** [comment]
FYI there is a plugin which supports this already on top of the shadow plugin: https://github.com/xpdustry/kotlin-shadow-relocator

But it would of course be nicer to have it work out-of-the-box 🙂

**Comment by Goooler** [comment]
Good to see! I'll push it to be bundled in this repo.

**Comment by Goooler** [comment]
I addressed the fix in #1539, but I have no idea how to test it. Reviews and suggestions are welcome!

**Comment by makeevrserg** [comment]
> I addressed the fix in [#1539](https://github.com/GradleUp/shadow/pull/1539), but I have no idea how to test it. Reviews and suggestions are welcome!

In issue #1622 I've provided sample project with kotlin's Exposed framework

I've tested with publishToMavenLocal and it seems, kotlin.Any still not found

And it's also seems, ShadowJar task became much slower

https://github.com/makeevrserg/ExposedGradleFail

**Comment by Goooler** [comment]
I'm fixing the Kotlin relocation stuff  first, no priority to investigate your issue filed in #1622.

**Comment by makeevrserg** [comment]
> I'm fixing the Kotlin relocation stuff first, no priority to investigate your issue filed in [#1622](https://github.com/GradleUp/shadow/issues/1622).

Turns out, my issue is actually affected by relocation stuff.  When repository's plugin applied [kotlin-shadow-relocator](https://github.com/xpdustry/kotlin-shadow-relocator), from which implementation and inspiration is taken, the problem is gone. But with #1539 it's still there

**Comment by Goooler** [comment]
Thanks for the investigation! I'll wait for some review feedback and then proceed with addressing the issue you reported.
